version: '3.8'

services:
  mysqlpool:
    build: ./
    command: ./mysqlpool
    ports:
      - "3333:3333"
    restart: always
    depends_on:
      - main
      - slave1
      - slave2

  main:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'main'
      MYSQL_ROOT_PASSWORD: 'main'
    ports:
      - "3308:3306"

  slave1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'slave1'
      MYSQL_ROOT_PASSWORD: 'slave1'
    ports:
      - "3309:3306"

  slave2:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'slave2'
      MYSQL_ROOT_PASSWORD: 'slave2'
    ports:
      - "3310:3306"
  